POST http://localhost:4000/add
Content-Type: application/json

{
    "name" : "Lunch Time",
    "priority" : "Low"
}

###

GET http://localhost:4000/list/5f2e4d1f71235b35344bf95d
###
PATCH http://localhost:4000/edit/5f2e4bce71235b35344bf95a
Content-Type: application/json

{
    "name" : "C# Forms Asp.net Framework",
    "priority" : "High"
}

### 
DELETE http://localhost:4000/delete/5f2e4bce71235b35344bf95a